import React, { useState, useMemo, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";
import { useBranchData } from "@/hooks/useBranchData";
import { 
  useGetInventoryMovementsQuery,
  useGetInventoryMovementStatisticsQuery,
  useGetAIInsightsQuery,
  useGetSmartAlertsQuery,
  useExportInventoryMovementsMutation
} from "@/services/inventoryMovementApi";
import { 
  Calendar as CalendarIcon, Download, Search, Filter, FileText, Package, TrendingUp, TrendingDown, 
  RotateCcw, AlertTriangle, Users, Eye, Plus, RefreshCw, BarChart3, Clock, MapPin, Bot, 
  Zap, Settings, Bell, Activity, Database, Target, Brain, Lightbulb, Cpu, Radar, 
  LineChart, PieChart, ArrowUpRight, ArrowDownRight, Minus, ChartBar, Hash, 
  Sparkles, Star, Award, Shield, Gauge, Copy
} from "lucide-react";

interface InventoryMovement {
  id: string;
  transactionDate: string;
  transactionType: string;
  itemCode: string;
  itemName: string;
  quantity: number;
  uom: string;
  warehouse: string;
  location: string;
  docRef: string;
  docType: string;
  user: string;
  cost: number;
  batchNumber?: string;
  expiryDate?: string;
  notes: string;
  balanceAfter: number;
  category?: string;
  supplier?: string;
  riskLevel?: 'low' | 'medium' | 'high';
  predictedDemand?: number;
  seasonalTrend?: 'increasing' | 'decreasing' | 'stable';
}

interface AIInsight {
  id: string;
  type: 'trend' | 'alert' | 'recommendation' | 'prediction';
  title: string;
  description: string;
  impact: 'high' | 'medium' | 'low';
  confidence: number;
  actionRequired: boolean;
  category: string;
}

interface SmartAlert {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  title: string;
  description: string;
  timestamp: string;
  resolved: boolean;
  autoGenerated: boolean;
}

const InventoryMovementLog = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("all");
  const [filterWarehouse, setFilterWarehouse] = useState("all");
  const [selectedPeriod, setSelectedPeriod] = useState("month");
  const [activeTab, setActiveTab] = useState("movements");
  const [selectedMovement, setSelectedMovement] = useState<InventoryMovement | null>(null);
  const [showDetailsDialog, setShowDetailsDialog] = useState(false);
  const [dateFrom, setDateFrom] = useState<Date>();
  const [dateTo, setDateTo] = useState<Date>();
  const [showAIAssistant, setShowAIAssistant] = useState(false);
  const [aiQuery, setAiQuery] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [selectedBranch, setSelectedBranch] = useState("all");
  const [showAdvancedFilters, setShowAdvancedFilters] = useState(false);
  const [realTimeUpdates, setRealTimeUpdates] = useState(true);
  const [notifications, setNotifications] = useState(true);
  const [autoRefresh, setAutoRefresh] = useState(5);
  const [lastUpdate, setLastUpdate] = useState(new Date());
  const [aiInsights, setAiInsights] = useState<AIInsight[]>([]);
  const [smartAlerts, setSmartAlerts] = useState<SmartAlert[]>([]);
  const [showAIPanel, setShowAIPanel] = useState(false);
  const [analyticsView, setAnalyticsView] = useState("overview");
  const [trendAnalysis, setTrendAnalysis] = useState<any[]>([]);
  const [predictiveMetrics, setPredictiveMetrics] = useState<any>({});
  const { toast } = useToast();
  const { branches } = useBranchData();

  // استخدام البيانات الحقيقية من API للرؤى والتنبيهات
  const { data: aiInsightsData, isLoading: aiInsightsLoading, error: aiInsightsError } = useGetAIInsightsQuery({}, {
    skip: !localStorage.getItem("authToken")
  });
  const { data: smartAlertsData, isLoading: smartAlertsLoading, error: smartAlertsError } = useGetSmartAlertsQuery({}, {
    skip: !localStorage.getItem("authToken")
  });

  // تحديث البيانات عند وصولها من API
  useEffect(() => {
    if (aiInsightsData) {
      setAiInsights(aiInsightsData);
    }
  }, [aiInsightsData]);

  useEffect(() => {
    if (smartAlertsData) {
      setSmartAlerts(smartAlertsData);
    }
  }, [smartAlertsData]);

  // Auto refresh functionality with AI updates
  useEffect(() => {
    if (realTimeUpdates) {
      const interval = setInterval(() => {
        setLastUpdate(new Date());
        // تحديث البيانات من API
        if (notifications) {
          toast({
            title: "تحديث ذكي",
            description: "تم تحديث البيانات والتحليلات",
          });
        }
      }, autoRefresh * 60 * 1000);

      return () => clearInterval(interval);
    }
  }, [realTimeUpdates, autoRefresh, notifications, toast]);



  // استخدام البيانات الحقيقية من API
  const { data: movementsData, isLoading: movementsLoading, error: movementsError } = useGetInventoryMovementsQuery({
    search: searchTerm,
    transactionType: filterType,
    warehouse: filterWarehouse,
    dateFrom: dateFrom?.toISOString(),
    dateTo: dateTo?.toISOString(),
    limit: 100
  });

  const movements = movementsData?.rows || [];

  const getTransactionTypeColor = (type: string) => {
    const colors = {
      "إدخال مشتريات": "bg-emerald-50 text-emerald-700 border-emerald-200",
      "إدخال مرتجع مبيعات": "bg-blue-50 text-blue-700 border-blue-200",
      "صرف مبيعات": "bg-rose-50 text-rose-700 border-rose-200",
      "صرف إنتاج": "bg-orange-50 text-orange-700 border-orange-200",
      "صرف استهلاك": "bg-purple-50 text-purple-700 border-purple-200",
      "تحويل داخلي": "bg-amber-50 text-amber-700 border-amber-200",
      "إدخال تحويل داخلي": "bg-cyan-50 text-cyan-700 border-cyan-200",
      "تسوية جرد": "bg-indigo-50 text-indigo-700 border-indigo-200",
      "إدخال تالف": "bg-slate-50 text-slate-700 border-slate-200",
      "إرجاع لمورد": "bg-pink-50 text-pink-700 border-pink-200"
    };
    return colors[type as keyof typeof colors] || "bg-slate-50 text-slate-700 border-slate-200";
  };

  const getTransactionIcon = (type: string) => {
    const icons = {
      "إدخال مشتريات": ArrowUpRight,
      "إدخال مرتجع مبيعات": RotateCcw,
      "صرف مبيعات": ArrowDownRight,
      "صرف إنتاج": Package,
      "صرف استهلاك": Minus,
      "تحويل داخلي": RotateCcw,
      "إدخال تحويل داخلي": ArrowUpRight,
      "تسوية جرد": FileText,
      "إدخال تالف": AlertTriangle,
      "إرجاع لمورد": RotateCcw
    };
    const IconComponent = icons[type as keyof typeof icons] || Package;
    return <IconComponent className="h-4 w-4" />;
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'trend': return TrendingUp;
      case 'alert': return AlertTriangle;
      case 'recommendation': return Lightbulb;
      case 'prediction': return Radar;
      default: return Brain;
    }
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'high': return 'text-red-600 bg-red-50';
      case 'medium': return 'text-yellow-600 bg-yellow-50';
      case 'low': return 'text-green-600 bg-green-50';
      default: return 'text-slate-600 bg-slate-50';
    }
  };

  const filteredMovements = useMemo(() => {
    return movements.filter(movement => {
      const matchesSearch = movement.itemName.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           movement.itemCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           movement.transactionType.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           movement.user.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           movement.docRef.toLowerCase().includes(searchTerm.toLowerCase());

      const matchesType = filterType === "all" || movement.transactionType === filterType;
      const matchesWarehouse = filterWarehouse === "all" || movement.warehouse === filterWarehouse;
      const matchesBranch = selectedBranch === "all" || movement.warehouse.includes(selectedBranch);

      return matchesSearch && matchesType && matchesWarehouse && matchesBranch;
    });
  }, [movements, searchTerm, filterType, filterWarehouse, selectedBranch]);

  const enhancedStatistics = useMemo(() => {
    const totalIn = filteredMovements.filter(m => m.quantity > 0).reduce((sum, m) => sum + m.quantity, 0);
    const totalOut = Math.abs(filteredMovements.filter(m => m.quantity < 0).reduce((sum, m) => sum + m.quantity, 0));
    const totalValue = filteredMovements.reduce((sum, m) => sum + (m.quantity * m.cost), 0);
    const uniqueItems = new Set(filteredMovements.map(m => m.itemCode)).size;
    const uniqueUsers = new Set(filteredMovements.map(m => m.user)).size;
    const averageTransactionValue = totalValue / filteredMovements.length || 0;
    const highRiskItems = movements.filter(m => m.riskLevel === 'high').length;
    const predictedShortage = movements.filter(m => m.predictedDemand && m.balanceAfter < m.predictedDemand).length;

    return { 
      totalIn, 
      totalOut, 
      totalValue, 
      uniqueItems, 
      uniqueUsers, 
      averageTransactionValue,
      highRiskItems,
      predictedShortage,
      efficiency: Math.round((totalIn / (totalIn + totalOut)) * 100) || 0,
      turnoverRate: Math.round(totalOut / uniqueItems * 100) / 100 || 0
    };
  }, [filteredMovements, movements]);

  // AI Analysis Functions
  const handleAIAnalysis = async () => {
    setIsLoading(true);
    try {
      // إعادة تحميل البيانات من API
      toast({
        title: "تحليل ذكي مكتمل",
        description: "تم إنجاز التحليل المتقدم وتوليد التوصيات",
      });
    } catch (error) {
      toast({
        title: "خطأ في التحليل",
        description: "فشل في إجراء التحليل الذكي",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleAIQuery = async () => {
    if (!aiQuery.trim()) return;
    
    setIsLoading(true);
    try {
      // إرسال الاستعلام إلى API
      toast({
        title: "استجابة المساعد الذكي",
        description: "تم إرسال استفسارك للتحليل الذكي",
      });
      setAiQuery("");
    } catch (error) {
      toast({
        title: "خطأ في الاستعلام",
        description: "فشل في معالجة الاستعلام",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleViewDetails = (movement: InventoryMovement) => {
    setSelectedMovement(movement);
    setShowDetailsDialog(true);
  };

  // استخدام API التصدير الحقيقي
  const [exportMovements, { isLoading: exportLoading }] = useExportInventoryMovementsMutation();

  const handleExport = async (format: string) => {
    setIsLoading(true);
    try {
      await exportMovements({
        search: searchTerm,
        transactionType: filterType,
        warehouse: filterWarehouse,
        dateFrom: dateFrom?.toISOString(),
        dateTo: dateTo?.toISOString(),
        format: format
      }).unwrap();

      toast({
        title: "تم التصدير بنجاح",
        description: `تم تصدير ${filteredMovements.length} حركة مع التحليلات`,
      });
    } catch (error) {
      toast({
        title: "خطأ في التصدير",
        description: "حدث خطأ أثناء تصدير البيانات",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container mx-auto p-6 space-y-6 bg-gradient-to-br from-slate-50 to-white min-h-screen">
      {/* Enhanced Header */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 via-purple-600 to-blue-800 p-8 text-white">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="relative z-10">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4 rtl:space-x-reverse">
              <div className="p-3 bg-white/20 rounded-2xl backdrop-blur-sm">
                <Database className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-3xl font-bold">سجل حركات المخزون المتطور</h1>
                <p className="text-white/80 mt-1">تحليلات ذكية ومراقبة في الوقت الفعلي</p>
              </div>
            </div>
            <div className="flex items-center space-x-3 rtl:space-x-reverse">
              <Button
                onClick={() => setShowAIPanel(!showAIPanel)}
                className="bg-white/20 hover:bg-white/30 text-white border-white/30"
                size="sm"
              >
                <Brain className="h-4 w-4 ml-2" />
                لوحة الذكاء الاصطناعي
              </Button>
              <div className="flex items-center space-x-2 rtl:space-x-reverse text-sm">
                <Activity className="h-4 w-4" />
                <span>آخر تحديث: {lastUpdate.toLocaleTimeString('ar-SA')}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AI Insights Panel */}
      {showAIPanel && (
        <Card className="border-2 border-blue-200 shadow-xl">
          <CardHeader className="bg-gradient-to-r from-blue-50 to-purple-50 border-b">
            <CardTitle className="flex items-center space-x-3 rtl:space-x-reverse text-blue-800">
              <Brain className="h-6 w-6" />
              <span>لوحة التحليلات الذكية</span>
            </CardTitle>
            {!localStorage.getItem("authToken") && (
              <div className="mt-2 p-2 bg-yellow-50 border border-yellow-200 rounded-lg">
                <div className="flex items-center text-yellow-800">
                  <AlertTriangle className="h-4 w-4 ml-2" />
                  <span className="text-sm">يرجى تسجيل الدخول لعرض التحليلات الذكية</span>
                </div>
              </div>
            )}
          </CardHeader>
          <CardContent className="p-6">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* AI Insights */}
              <div className="lg:col-span-2">
                <h3 className="text-lg font-semibold mb-4 flex items-center">
                  <Lightbulb className="h-5 w-5 ml-2 text-yellow-500" />
                  رؤى ذكية
                </h3>
                <div className="space-y-3">
                  {aiInsightsLoading ? (
                    <div className="text-center py-4">
                      <RefreshCw className="h-6 w-6 animate-spin mx-auto text-blue-600 mb-2" />
                      <p className="text-sm text-slate-600">جاري تحميل الرؤى الذكية...</p>
                    </div>
                  ) : aiInsightsError ? (
                    <div className="text-center py-4">
                      <AlertTriangle className="h-6 w-6 text-red-600 mx-auto mb-2" />
                      <p className="text-sm text-red-600">خطأ في تحميل الرؤى الذكية</p>
                      <p className="text-xs text-red-500 mt-1">
                        {aiInsightsError?.data?.message || 'يرجى تسجيل الدخول أولاً'}
                      </p>
                    </div>
                  ) : aiInsights.length === 0 ? (
                    <div className="text-center py-4">
                      <Brain className="h-6 w-6 text-slate-400 mx-auto mb-2" />
                      <p className="text-sm text-slate-600">لا توجد رؤى ذكية متاحة</p>
                    </div>
                  ) : (
                    aiInsights.map((insight) => {
                    const IconComponent = getInsightIcon(insight.type);
                    return (
                      <div key={insight.id} className="p-4 bg-slate-50 rounded-xl border">
                        <div className="flex items-start justify-between">
                          <div className="flex items-start space-x-3 rtl:space-x-reverse">
                            <div className={`p-2 rounded-lg ${getImpactColor(insight.impact)}`}>
                              <IconComponent className="h-4 w-4" />
                            </div>
                            <div className="flex-1">
                              <h4 className="font-medium text-slate-900">{insight.title}</h4>
                              <p className="text-sm text-slate-600 mt-1">{insight.description}</p>
                              <div className="flex items-center mt-2 space-x-4 rtl:space-x-reverse text-xs">
                                <span className="flex items-center">
                                  <Gauge className="h-3 w-3 ml-1" />
                                  الثقة: {insight.confidence}%
                                </span>
                                <Badge variant="outline" className="text-xs">
                                  {insight.category}
                                </Badge>
                              </div>
                            </div>
                          </div>
                          {insight.actionRequired && (
                            <Badge variant="destructive" className="text-xs">
                              يتطلب إجراء
                            </Badge>
                          )}
                        </div>
                      </div>
                    );
                    })
                  )}
                </div>
              </div>

              {/* Smart Alerts */}
              <div>
                <h3 className="text-lg font-semibold mb-4 flex items-center">
                  <Bell className="h-5 w-5 ml-2 text-red-500" />
                  تنبيهات ذكية
                </h3>
                <div className="space-y-3">
                  {smartAlertsLoading ? (
                    <div className="text-center py-4">
                      <RefreshCw className="h-6 w-6 animate-spin mx-auto text-blue-600 mb-2" />
                      <p className="text-sm text-slate-600">جاري تحميل التنبيهات...</p>
                    </div>
                  ) : smartAlertsError ? (
                    <div className="text-center py-4">
                      <AlertTriangle className="h-6 w-6 text-red-600 mx-auto mb-2" />
                      <p className="text-sm text-red-600">خطأ في تحميل التنبيهات</p>
                      <p className="text-xs text-red-500 mt-1">
                        {smartAlertsError?.data?.message || 'يرجى تسجيل الدخول أولاً'}
                      </p>
                    </div>
                  ) : smartAlerts.length === 0 ? (
                    <div className="text-center py-4">
                      <Bell className="h-6 w-6 text-slate-400 mx-auto mb-2" />
                      <p className="text-sm text-slate-600">لا توجد تنبيهات متاحة</p>
                    </div>
                  ) : (
                    smartAlerts.map((alert) => (
                    <div key={alert.id} className={`p-3 rounded-lg border-l-4 ${
                      alert.severity === 'critical' ? 'border-red-500 bg-red-50' :
                      alert.severity === 'warning' ? 'border-yellow-500 bg-yellow-50' :
                      'border-blue-500 bg-blue-50'
                    }`}>
                      <div className="flex items-center justify-between mb-1">
                        <h4 className="font-medium text-sm">{alert.title}</h4>
                        <Badge variant={alert.severity === 'critical' ? 'destructive' : 'secondary'} className="text-xs">
                          {alert.severity}
                        </Badge>
                      </div>
                      <p className="text-xs text-slate-600">{alert.description}</p>
                      {alert.autoGenerated && (
                        <div className="flex items-center mt-2">
                          <Bot className="h-3 w-3 ml-1 text-blue-500" />
                          <span className="text-xs text-blue-600">مُولد تلقائياً</span>
                        </div>
                      )}
                    </div>
                    ))
                  )}
                </div>
              </div>
            </div>

            {/* AI Assistant */}
            <div className="mt-6 p-4 bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl border space-y-4">
              <h3 className="font-semibold mb-3 flex items-center">
                <Bot className="h-5 w-5 ml-2 text-purple-600" />
                المساعد الذكي
              </h3>
              <div className="flex space-x-3 rtl:space-x-reverse">
                <Input
                  placeholder="اسأل عن تحليلات المخزون أو اطلب توصيات..."
                  value={aiQuery}
                  onChange={(e) => setAiQuery(e.target.value)}
                  className="flex-1"
                  onKeyPress={(e) => e.key === 'Enter' && handleAIQuery()}
                />
                <Button onClick={handleAIQuery} disabled={isLoading} className="bg-purple-600 hover:bg-purple-700">
                  {isLoading ? <Zap className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}
                </Button>
                <Button onClick={handleAIAnalysis} disabled={isLoading} variant="outline">
                  {isLoading ? <Cpu className="h-4 w-4 animate-spin" /> : <Cpu className="h-4 w-4" />}
                  تحليل شامل
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Enhanced Statistics Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card className="overflow-hidden border-0 shadow-lg bg-gradient-to-br from-green-50 to-emerald-50">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-emerald-700">إجمالي الداخل</p>
                <p className="text-3xl font-bold text-emerald-900">{enhancedStatistics.totalIn.toLocaleString()}</p>
                <p className="text-xs text-emerald-600 mt-1">معدل الكفاءة: {enhancedStatistics.efficiency}%</p>
              </div>
              <div className="p-3 bg-emerald-100 rounded-full">
                <ArrowUpRight className="h-6 w-6 text-emerald-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="overflow-hidden border-0 shadow-lg bg-gradient-to-br from-red-50 to-rose-50">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-rose-700">إجمالي الخارج</p>
                <p className="text-3xl font-bold text-rose-900">{enhancedStatistics.totalOut.toLocaleString()}</p>
                <p className="text-xs text-rose-600 mt-1">معدل الدوران: {enhancedStatistics.turnoverRate}</p>
              </div>
              <div className="p-3 bg-rose-100 rounded-full">
                <ArrowDownRight className="h-6 w-6 text-rose-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="overflow-hidden border-0 shadow-lg bg-gradient-to-br from-blue-50 to-cyan-50">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-blue-700">القيمة الإجمالية</p>
                <p className="text-2xl font-bold text-blue-900">{enhancedStatistics.totalValue.toLocaleString()} جنية مصري</p>
                <p className="text-xs text-blue-600 mt-1">متوسط الحركة: {enhancedStatistics.averageTransactionValue.toFixed(0)} جنية مصري</p>
              </div>
              <div className="p-3 bg-blue-100 rounded-full">
                <ChartBar className="h-6 w-6 text-blue-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="overflow-hidden border-0 shadow-lg bg-gradient-to-br from-purple-50 to-violet-50">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-purple-700">تنبيهات المخاطر</p>
                <p className="text-3xl font-bold text-purple-900">{enhancedStatistics.highRiskItems}</p>
                <p className="text-xs text-purple-600 mt-1">نقص متوقع: {enhancedStatistics.predictedShortage}</p>
              </div>
              <div className="p-3 bg-purple-100 rounded-full">
                <Shield className="h-6 w-6 text-purple-600" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Enhanced Filters and Controls */}
      <Card className="shadow-lg border-0">
        <CardContent className="p-6">
          <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
            <div className="relative">
              <Search className="absolute right-3 top-3 h-4 w-4 text-slate-400" />
              <Input
                placeholder="البحث في الحركات..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pr-10"
              />
            </div>
            
            <Select value={filterType} onValueChange={setFilterType}>
              <SelectTrigger>
                <SelectValue placeholder="نوع الحركة" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">جميع الأنواع</SelectItem>
                <SelectItem value="إدخال مشتريات">إدخال مشتريات</SelectItem>
                <SelectItem value="صرف مبيعات">صرف مبيعات</SelectItem>
                <SelectItem value="تحويل داخلي">تحويل داخلي</SelectItem>
                <SelectItem value="تسوية جرد">تسوية جرد</SelectItem>
              </SelectContent>
            </Select>

            <Select value={filterWarehouse} onValueChange={setFilterWarehouse}>
              <SelectTrigger>
                <SelectValue placeholder="المخزن" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">جميع المخازن</SelectItem>
                <SelectItem value="المخزن الرئيسي">المخزن الرئيسي</SelectItem>
                <SelectItem value="مخزن الفرع">مخزن الفرع</SelectItem>
              </SelectContent>
            </Select>

            <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
              <SelectTrigger>
                <SelectValue placeholder="الفترة الزمنية" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">جميع الفترات</SelectItem>
                <SelectItem value="day">اليوم</SelectItem>
                <SelectItem value="week">الأسبوع</SelectItem>
                <SelectItem value="month">الشهر</SelectItem>
              </SelectContent>
            </Select>

            <div className="flex space-x-2 rtl:space-x-reverse">
              <Button 
                onClick={() => handleExport('csv')}
                className="bg-green-600 hover:bg-green-700 flex-1"
                size="sm"
              >
                <Download className="h-4 w-4 ml-1" />
                تصدير
              </Button>
              <Button 
                onClick={() => setShowAdvancedFilters(!showAdvancedFilters)}
                variant="outline"
                size="sm"
              >
                <Filter className="h-4 w-4" />
              </Button>
            </div>
          </div>

          {/* Advanced Filters */}
          {showAdvancedFilters && (
            <div className="mt-4 p-4 bg-slate-50 rounded-xl border space-y-4">
              <h4 className="font-medium text-slate-900">فلاتر متقدمة</h4>
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-2">من تاريخ</label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button variant="outline" className="w-full justify-start text-right">
                        <CalendarIcon className="ml-2 h-4 w-4" />
                        {dateFrom ? dateFrom.toLocaleDateString('ar-SA') : "اختر التاريخ"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={dateFrom}
                        onSelect={setDateFrom}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">إلى تاريخ</label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button variant="outline" className="w-full justify-start text-right">
                        <CalendarIcon className="ml-2 h-4 w-4" />
                        {dateTo ? dateTo.toLocaleDateString('ar-SA') : "اختر التاريخ"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={dateTo}
                        onSelect={setDateTo}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-medium">التحديث التلقائي</label>
                    <Switch checked={realTimeUpdates} onCheckedChange={setRealTimeUpdates} />
                  </div>
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-medium">التنبيهات</label>
                    <Switch checked={notifications} onCheckedChange={setNotifications} />
                  </div>
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Enhanced Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <div className="flex items-center justify-between">
          <TabsList className="grid w-full max-w-2xl grid-cols-4 bg-slate-100 p-1">
            <TabsTrigger value="movements" className="data-[state=active]:bg-white">
              سجل الحركات
            </TabsTrigger>
            <TabsTrigger value="analytics" className="data-[state=active]:bg-white">
              التحليلات المتقدمة
            </TabsTrigger>
            <TabsTrigger value="predictions" className="data-[state=active]:bg-white">
              التنبؤات الذكية
            </TabsTrigger>
            <TabsTrigger value="reports" className="data-[state=active]:bg-white">
              التقارير الشاملة
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="movements">
          <Card className="shadow-lg border-0">
            <CardHeader className="bg-gradient-to-r from-slate-50 to-white border-b">
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center">
                  <Package className="h-5 w-5 ml-2" />
                  سجل الحركات المفصل
                </span>
                <Badge variant="secondary" className="px-3 py-1">
                  {filteredMovements.length} حركة
                </Badge>
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              {movementsLoading ? (
                <div className="flex items-center justify-center h-[400px]">
                  <div className="text-center">
                    <RefreshCw className="h-8 w-8 animate-spin mx-auto text-blue-600 mb-4" />
                    <p className="text-slate-600">جاري تحميل البيانات...</p>
                  </div>
                </div>
              ) : movementsError ? (
                <div className="flex items-center justify-center h-[400px]">
                  <div className="text-center">
                    <AlertTriangle className="h-8 w-8 text-red-600 mx-auto mb-4" />
                    <p className="text-red-600 mb-2">حدث خطأ في تحميل البيانات</p>
                    <p className="text-sm text-red-500 mb-4">
                      {movementsError?.data?.message || movementsError?.message || 'خطأ غير معروف'}
                    </p>
                    <Button onClick={() => window.location.reload()} variant="outline">
                      إعادة المحاولة
                    </Button>
                  </div>
                </div>
              ) : filteredMovements.length === 0 ? (
                <div className="flex items-center justify-center h-[400px]">
                  <div className="text-center">
                    <Package className="h-8 w-8 text-slate-400 mx-auto mb-4" />
                    <p className="text-slate-600">لا توجد حركات مخزون</p>
                  </div>
                </div>
              ) : (
              <ScrollArea className="h-[600px]">
                <Table>
                  <TableHeader className="sticky top-0 bg-white shadow-sm">
                    <TableRow>
                      <TableHead className="text-right font-semibold">التاريخ والوقت</TableHead>
                      <TableHead className="text-right font-semibold">نوع الحركة</TableHead>
                      <TableHead className="text-right font-semibold">الصنف</TableHead>
                      <TableHead className="text-right font-semibold">الكمية</TableHead>
                      <TableHead className="text-right font-semibold">المخزن</TableHead>
                      <TableHead className="text-right font-semibold">المستخدم</TableHead>
                      <TableHead className="text-right font-semibold">الرصيد</TableHead>
                      <TableHead className="text-right font-semibold">التحليل الذكي</TableHead>
                      <TableHead className="text-right font-semibold">إجراءات</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredMovements.map((movement) => (
                      <TableRow key={movement.id} className="hover:bg-slate-50 transition-colors">
                        <TableCell className="font-medium">
                          <div>
                              <div className="text-sm">{new Date(movement.transactionDate).toLocaleDateString('ar-SA')}</div>
                              <div className="text-xs text-slate-500">{new Date(movement.transactionDate).toLocaleTimeString('ar-SA')}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge className={`${getTransactionTypeColor(movement.transactionType)} border`}>
                            <span className="ml-1">{getTransactionIcon(movement.transactionType)}</span>
                            {movement.transactionType}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div>
                            <div className="font-medium text-sm">{movement.itemName}</div>
                            <div className="text-xs text-slate-500">{movement.itemCode}</div>
                            {movement.category && (
                              <Badge variant="outline" className="mt-1 text-xs">{movement.category}</Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center">
                            <span className={`font-bold ${movement.quantity > 0 ? 'text-green-600' : 'text-red-600'}`}>
                              {movement.quantity > 0 ? '+' : ''}{movement.quantity}
                            </span>
                            <span className="text-xs text-slate-500 mr-1">{movement.uom}</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div>
                            <div className="text-sm">{movement.warehouse}</div>
                            <div className="text-xs text-slate-500">{movement.location}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center">
                            <Users className="h-3 w-3 ml-1 text-slate-400" />
                              <span className="text-sm">{movement.userId}</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-right">
                            <div className="font-medium">{movement.balanceAfter}</div>
                            <div className="text-xs text-slate-500">{movement.uom}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="space-y-1">
                            {movement.riskLevel && (
                              <Badge 
                                variant={movement.riskLevel === 'high' ? 'destructive' : 
                                        movement.riskLevel === 'medium' ? 'secondary' : 'default'}
                                className="text-xs"
                              >
                                {movement.riskLevel === 'high' ? 'عالي المخاطر' : 
                                 movement.riskLevel === 'medium' ? 'متوسط المخاطر' : 'منخفض المخاطر'}
                              </Badge>
                            )}
                            {movement.predictedDemand && (
                              <div className="text-xs text-blue-600">
                                طلب متوقع: {movement.predictedDemand}
                              </div>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleViewDetails(movement)}
                          >
                            <Eye className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </ScrollArea>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="analytics">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="shadow-lg border-0">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <LineChart className="h-5 w-5 ml-2 text-blue-600" />
                  تحليل الاتجاهات
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="p-4 bg-blue-50 rounded-lg">
                    <h4 className="font-medium text-blue-900">الاتجاه العام</h4>
                    <p className="text-sm text-blue-700 mt-1">زيادة في النشاط بنسبة 15% هذا الشهر</p>
                    <Progress value={75} className="mt-2" />
                  </div>
                  <div className="p-4 bg-green-50 rounded-lg">
                    <h4 className="font-medium text-green-900">كفاءة العمليات</h4>
                    <p className="text-sm text-green-700 mt-1">تحسن بنسبة 8% في سرعة المعالجة</p>
                    <Progress value={85} className="mt-2" />
                  </div>
                  <div className="p-4 bg-yellow-50 rounded-lg">
                    <h4 className="font-medium text-yellow-900">مستوى المخزون</h4>
                    <p className="text-sm text-yellow-700 mt-1">استقرار في المستويات مع انخفاض طفيف</p>
                    <Progress value={68} className="mt-2" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-0">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <PieChart className="h-5 w-5 ml-2 text-purple-600" />
                  توزيع العمليات
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    { type: "إدخال مشتريات", percentage: 35, color: "bg-green-500" },
                    { type: "صرف مبيعات", percentage: 28, color: "bg-red-500" },
                    { type: "تحويل داخلي", percentage: 20, color: "bg-yellow-500" },
                    { type: "تسوية جرد", percentage: 17, color: "bg-blue-500" }
                  ].map((item) => (
                    <div key={item.type} className="flex items-center justify-between">
                      <div className="flex items-center space-x-3 rtl:space-x-reverse">
                        <div className={`w-3 h-3 rounded-full ${item.color}`}></div>
                        <span className="text-sm">{item.type}</span>
                      </div>
                      <span className="font-medium">{item.percentage}%</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="predictions">
          <Card className="shadow-lg border-0">
            <CardHeader className="bg-gradient-to-r from-purple-50 to-blue-50 border-b">
              <CardTitle className="flex items-center">
                <Radar className="h-5 w-5 ml-2 text-purple-600" />
                التنبؤات الذكية والتوصيات
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div>
                  <h3 className="font-semibold mb-4 text-purple-900">توقعات الطلب القادمة</h3>
                  <div className="space-y-4">
                    {[
                      { item: "مواد تنظيف - ديتول", current: 125, predicted: 145, trend: "up" },
                      { item: "ورق طباعة A4", current: 200, predicted: 180, trend: "down" },
                      { item: "مستلزمات مكتبية", current: 45, predicted: 52, trend: "up" }
                    ].map((prediction) => (
                      <div key={prediction.item} className="p-4 bg-white border rounded-lg">
                        <div className="flex items-center justify-between mb-2">
                          <h4 className="font-medium">{prediction.item}</h4>
                          <Badge className={prediction.trend === 'up' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}>
                            {prediction.trend === 'up' ? 'ارتفاع' : 'انخفاض'}
                          </Badge>
                        </div>
                        <div className="flex items-center justify-between text-sm">
                          <span>الحالي: {prediction.current}</span>
                          <span>المتوقع: {prediction.predicted}</span>
                        </div>
                        <Progress 
                          value={(prediction.predicted / prediction.current) * 50} 
                          className="mt-2" 
                        />
                      </div>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-4 text-blue-900">توصيات التحسين</h3>
                  <div className="space-y-4">
                    {[
                      {
                        title: "تحسين مستويات الأمان",
                        description: "زيادة مخزون الأمان لمواد التنظيف بنسبة 10%",
                        priority: "high",
                        impact: "تجنب انقطاع المخزون"
                      },
                      {
                        title: "تحسين دورة الطلب",
                        description: "تقليل فترة الطلب للمستلزمات المكتبية",
                        priority: "medium",
                        impact: "توفير 5% من تكاليف التخزين"
                      },
                      {
                        title: "مراجعة المورد",
                        description: "تقييم أداء مورد الورق والبحث عن بدائل",
                        priority: "low",
                        impact: "تحسين الجودة والسعر"
                      }
                    ].map((recommendation, index) => (
                      <div key={index} className="p-4 bg-white border rounded-lg">
                        <div className="flex items-start justify-between mb-2">
                          <h4 className="font-medium">{recommendation.title}</h4>
                          <Badge className={
                            recommendation.priority === 'high' ? 'bg-red-100 text-red-800' :
                            recommendation.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-green-100 text-green-800'
                          }>
                            {recommendation.priority === 'high' ? 'عالي' :
                             recommendation.priority === 'medium' ? 'متوسط' : 'منخفض'}
                          </Badge>
                        </div>
                        <p className="text-sm text-slate-600 mb-2">{recommendation.description}</p>
                        <div className="flex items-center text-xs text-blue-600">
                          <Star className="h-3 w-3 ml-1" />
                          التأثير المتوقع: {recommendation.impact}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="reports">
          <Card className="shadow-lg border-0">
            <CardHeader className="bg-gradient-to-r from-slate-50 to-white border-b">
              <CardTitle className="flex items-center">
                <FileText className="h-5 w-5 ml-2 text-slate-600" />
                التقارير الشاملة والملخصات
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2">
                  <h3 className="font-semibold mb-4">ملخص الأداء الشامل</h3>
                  <div className="bg-gradient-to-r from-blue-50 to-purple-50 p-6 rounded-xl border">
                    <div className="grid grid-cols-2 gap-4 mb-4">
                      <div className="text-center">
                        <div className="text-2xl font-bold text-blue-900">{enhancedStatistics.totalIn + enhancedStatistics.totalOut}</div>
                        <div className="text-sm text-blue-700">إجمالي الحركات</div>
                      </div>
                      <div className="text-center">
                        <div className="text-2xl font-bold text-purple-900">{enhancedStatistics.efficiency}%</div>
                        <div className="text-sm text-purple-700">معدل الكفاءة</div>
                      </div>
                    </div>
                    <Separator className="my-4" />
                    <div className="space-y-3">
                      <div className="flex justify-between">
                        <span>أعلى معدل استهلاك:</span>
                        <span className="font-medium">مواد التنظيف</span>
                      </div>
                      <div className="flex justify-between">
                        <span>أكثر المستخدمين نشاطاً:</span>
                        <span className="font-medium">أحمد محمد</span>
                      </div>
                      <div className="flex justify-between">
                        <span>المخزن الأكثر حركة:</span>
                        <span className="font-medium">المخزن الرئيسي</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-4">تقارير سريعة</h3>
                  <div className="space-y-3">
                    {[
                      { name: "تقرير الحركات اليومية", icon: Clock },
                      { name: "تقرير تحليل المخزون", icon: BarChart3 },
                      { name: "تقرير الأداء الشهري", icon: Activity },
                      { name: "تقرير التنبؤات", icon: Radar }
                    ].map((report) => (
                      <Button
                        key={report.name}
                        variant="outline"
                        className="w-full justify-start h-auto p-4"
                        onClick={() => toast({
                          title: "جاري تحضير التقرير",
                          description: `سيتم إنشاء ${report.name} قريباً`,
                        })}
                      >
                        <report.icon className="h-4 w-4 ml-2" />
                        <div className="text-right">
                          <div className="font-medium">{report.name}</div>
                        </div>
                      </Button>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Enhanced Details Dialog */}
      <Dialog open={showDetailsDialog} onOpenChange={setShowDetailsDialog}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center space-x-3 rtl:space-x-reverse">
              <Package className="h-6 w-6 text-blue-600" />
              <span>تفاصيل الحركة المتقدمة</span>
            </DialogTitle>
          </DialogHeader>
          {selectedMovement && (
            <div className="space-y-6">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">معلومات أساسية</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex justify-between">
                      <span className="text-slate-600">رقم الحركة:</span>
                      <span className="font-medium">{selectedMovement.id}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">التاريخ والوقت:</span>
                      <span className="font-medium">{selectedMovement.transactionDate}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">نوع الحركة:</span>
                      <Badge className={getTransactionTypeColor(selectedMovement.transactionType)}>
                        {selectedMovement.transactionType}
                      </Badge>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">المستخدم:</span>
                          <span className="font-medium">{selectedMovement.userId}</span>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">معلومات الصنف</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex justify-between">
                      <span className="text-slate-600">كود الصنف:</span>
                      <span className="font-medium">{selectedMovement.itemCode}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">اسم الصنف:</span>
                      <span className="font-medium">{selectedMovement.itemName}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">الكمية:</span>
                      <span className={`font-bold ${selectedMovement.quantity > 0 ? 'text-green-600' : 'text-red-600'}`}>
                        {selectedMovement.quantity > 0 ? '+' : ''}{selectedMovement.quantity} {selectedMovement.uom}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-600">الرصيد بعد الحركة:</span>
                      <span className="font-medium">{selectedMovement.balanceAfter} {selectedMovement.uom}</span>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* AI Analysis Section */}
              <Card className="border-blue-200">
                <CardHeader className="bg-blue-50">
                  <CardTitle className="flex items-center text-blue-800">
                    <Brain className="h-5 w-5 ml-2" />
                    التحليل الذكي للحركة
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4">
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                    <div className="text-center p-3 bg-green-50 rounded-lg">
                      <Shield className="h-6 w-6 mx-auto text-green-600 mb-2" />
                      <div className="text-sm font-medium text-green-800">مستوى المخاطر</div>
                      <div className="text-lg font-bold text-green-900">
                        {selectedMovement.riskLevel === 'low' ? 'منخفض' :
                         selectedMovement.riskLevel === 'medium' ? 'متوسط' : 'عالي'}
                      </div>
                    </div>
                    <div className="text-center p-3 bg-blue-50 rounded-lg">
                      <Target className="h-6 w-6 mx-auto text-blue-600 mb-2" />
                      <div className="text-sm font-medium text-blue-800">الطلب المتوقع</div>
                      <div className="text-lg font-bold text-blue-900">
                        {selectedMovement.predictedDemand || 'غير محدد'}
                      </div>
                    </div>
                    <div className="text-center p-3 bg-purple-50 rounded-lg">
                      <TrendingUp className="h-6 w-6 mx-auto text-purple-600 mb-2" />
                      <div className="text-sm font-medium text-purple-800">الاتجاه الموسمي</div>
                      <div className="text-lg font-bold text-purple-900">
                        {selectedMovement.seasonalTrend === 'increasing' ? 'متزايد' :
                         selectedMovement.seasonalTrend === 'decreasing' ? 'متناقص' : 'مستقر'}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <div className="flex justify-end space-x-3 rtl:space-x-reverse">
                <Button variant="outline" onClick={() => setShowDetailsDialog(false)}>
                  إغلاق
                </Button>
                <Button 
                  onClick={() => {
                    toast({
                      title: "تم النسخ",
                      description: "تم نسخ تفاصيل الحركة",
                    });
                  }}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  <Copy className="h-4 w-4 ml-1" />
                  نسخ التفاصيل
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default InventoryMovementLog;
