const { DataTypes } = require('sequelize');
const sequelize = require('../Config/sequelize');

const SmartAlert = sequelize.define('SmartAlert', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  severity: {
    type: DataTypes.ENUM('critical', 'warning', 'info'),
    allowNull: false,
    defaultValue: 'info'
  },
  title: {
    type: DataTypes.STRING(255),
    allowNull: false
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: false
  },
  timestamp: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  },
  resolved: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  alertType: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  relatedItemId: {
    type: DataTypes.INTEGER,
    allowNull: true
  },
  relatedItemType: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  priority: {
    type: DataTypes.INTEGER,
    defaultValue: 1,
    validate: {
      min: 1,
      max: 5
    }
  },
  companyId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Companies',
      key: 'id'
    }
  },
  branchId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'Branches',
      key: 'id'
    }
  },
  isActive: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  createdAt: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW
  },
  updatedAt: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW
  }
}, {
  tableName: 'SMART_ALERTS',
  timestamps: true,
  indexes: [
    {
      fields: ['severity']
    },
    {
      fields: ['resolved']
    },
    {
      fields: ['timestamp']
    },
    {
      fields: ['companyId']
    },
    {
      fields: ['branchId']
    },
    {
      fields: ['priority']
    }
  ]
});

module.exports = SmartAlert;
